Repository codesquad-member-2020/dust-10, pull requests merged in 2020-04, with the labels that each got.

#14 Feature/html/#11
  FE/_config.yml
  FE/src/js/index.js
  FE/src/js/index_test.js
  FE/src/page/index.html
Labels: FE, HTML

#23 Feature/js/#18
  FE/src/js/dust/dustGrade.js
Labels: FE, js

#24 Feature/js/#21
  FE/src/js/dust/dustGrape.js
Labels: FE, js

#25 [feature/forecast-BE] 코드 리팩토링 완료
  BE/.gitignore
  BE/.keep
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/dust10/group10/Group10Application.java
  BE/src/main/java/com/dust10/group10/api/ApiResponse.java
  BE/src/main/java/com/dust10/group10/config/WebConfig.java
  BE/src/main/java/com/dust10/group10/controller/ForecastController.java
  BE/src/main/java/com/dust10/group10/domain/Station.java
  BE/src/main/java/com/dust10/group10/service/ForecastService.java
  BE/src/main/java/com/dust10/group10/service/LocationService.java
  BE/src/main/java/com/dust10/group10/utils/OpenApiConnect.java
  BE/src/main/java/com/dust10/group10/utils/OpenApiURL.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/dust10/group10/Group10ApplicationTests.java
Labels: BE, Refactoring

#26 Feature/js/#22
  FE/src/css/style.css
  FE/src/js/dust/dustTouch.js
Labels: FE, js

#32 Feature/js/#29
  FE/src/js/dust/main.js
  FE/src/page/index.html
Labels: FE, js

#34 Feature/js/#33
  FE/src/constants/grade.js
  FE/src/js/dust/dustGrade.js
  FE/src/js/dust/dustGrape.js
  FE/src/js/dust/main.js
Labels: FE, js

#38 미세먼지 예보 기능 추가
  BE/src/main/java/com/dust10/group10/api/ApiResponse.java
  BE/src/main/java/com/dust10/group10/config/WebConfig.java
  BE/src/main/java/com/dust10/group10/controller/ForecastController.java
  BE/src/main/java/com/dust10/group10/domain/DustStatus.java
  BE/src/main/java/com/dust10/group10/domain/Forecast.java
  BE/src/main/java/com/dust10/group10/service/ForecastService.java
  BE/src/main/java/com/dust10/group10/service/LocationService.java
  BE/src/main/java/com/dust10/group10/utils/OpenApiConnect.java
  BE/src/main/java/com/dust10/group10/utils/OpenApiURL.java
Labels: BE

#39 Feature/js/#35
  FE/src/constants/coordinate.js
  FE/src/js/dust/dustTouch.js
  FE/src/js/dust/main.js
  FE/src/option/touchOption.js
  FE/src/page/index.html
Labels: FE, js

#40 Feature/js/#36
  FE/src/.gitignore
  FE/src/data/mockdata.json
  FE/src/js/dust/main.js
  FE/src/package-lock.json
  FE/src/package.json
  FE/src/page/index.html
  FE/src/public/dust_bundle.js
  FE/src/webpack.config.js
Labels: Build_webpack, FE, js

#45 프론트엔드 최종 배포
  FE/src/.gitignore
  FE/src/constants/coordinate.js
  FE/src/constants/grade.js
  FE/src/css/forecast.css
  FE/src/css/reset.css
  FE/src/css/style.css
  FE/src/js/dust/dustGrade.js
  FE/src/js/dust/dustGrape.js
  FE/src/js/dust/dustTouch.js
  FE/src/js/dust/main.js
  FE/src/js/forecast/fetchData.js
  FE/src/js/forecast/forecast.js
  FE/src/js/forecast/main.js
  FE/src/js/forecast/util.js
  FE/src/option/dustPageDom.js
  FE/src/option/touchOption.js
  FE/src/package-lock.json
  FE/src/package.json
  FE/src/page/forecast.html
  FE/src/page/index.html
  FE/src/public/dust_bundle.js
  FE/src/public/forecast_bundle.js
  FE/src/webpack.config.js
Labels: FE
